config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resource :user, only: [:show, :edit, :update]
  resources :pools
  resources :bookings, only: [:create, :update]
  root to: 'pages#home'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  # belongs_to :guest, class_name: 'User', foreign_key: :guest_id
  belongs_to :user, dependent: :destroy
  belongs_to :pool, dependent: :destroy

  validates :user, presence: true
  validates :pool, presence: true
  validates :status, inclusion: {in: %w(Pending Confirmed Refused), allow_nil: false}
  validates :checkin_on, presence: true
  validates :length,  inclusion: {in: ['Morning', 'Afternoon', 'All Day', 'All Night Long'], allow_nil: false}

end

app/models/pool.rb
class Pool < ActiveRecord::Base
  # belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  belongs_to :user, dependent: :destroy
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, presence: true
  validates :address, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :capacity, numericality: { only_integer: true } # "nil" is not accepted as not an integer!
  validates :user, presence: true

  has_attached_file :picture,
    styles: {
      large: "1400x933>",
      medium: "350x233>",
      thumbnail: "70x40>"},
      default_url: "default_:style.jpg"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :picture,
    styles: { normal: "200x200#" },
    default_url: "default-avatar.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [ :facebook ]

  has_many :bookings
  has_many :pools
  has_many :requests, through: :pools, source: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.facebook_picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end

  def profile_picture
    if self.picture.exists?
      self.picture.url(:normal)
    end
    if ! self.picture.url().include? "default"
      pic = self.picture.url(:normal)
    elsif self.provider
      pic = self.facebook_picture
    else
      pic = self.picture.url(:normal)
    end
    return pic
  end

  def notifications
    # if new booking sur ma pool
    new_book = 0
    self.pools.each do |pool|
      pool.bookings.each do |booking|
        p booking
        if booking.new_not
          new_book += 1
        end
      end
    end
    p "=====debug new book======"
    p new_book
    return new_book
    # rand(0..1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name,  :last_name]
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    params[:pool_id] = params[:pool_id].to_i
    params[:user_id] = params[:user_id].to_i
    @booking = Booking.new(booking_params)
    @booking.new_not = true
    @booking.save
    redirect_to user_path
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.new_not = false
    @booking.update(status: params[:status])
    redirect_to user_path
  end

  private

  def booking_params
    params.require(:booking).permit(:pool_id, :user_id, :checkin_on, :length, :status, :new_not)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @home_page = true
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  #before_action :find_user, only: [:create]


  def index

    # params
    @city = params[:city]
    @checkin_on = params[:checkin_on]
    @length = params[:length]
    @nb_results = Pool.near(@city, 10).size
    if @nb_results == 0
      @pools = Pool.all
    else
      @pools = Pool.near(@city, 10)
    end
    p "=== debug ===="
    p @nb_results
    p @pools

    # Gmaps markers
    @markers = Gmaps4rails.build_markers(@pools) do |pool, marker|
      p marker.lat pool.latitude
      p marker.lng pool.longitude
    end
  end

  def show
    @checkin_on = params[:checkin_on] || ""
    @length = params[:length] || " "

     # message to user
    if @checkin_on == ""
      @message_to_user = "Please choose a date"
    else
      @message_to_user = " "
    end

    if params[:length]
      @length_selection = [@length, "Morning", "Afternoon", "All Day", "All Night Long"].uniq
    else
      @length_selection = ["Morning", "Afternoon", "All Day", "All Night Long"]
    end

    # get pool
    @pool = Pool.find(params[:id])
    @booking = Booking.new

    # Gmaps marker
    @markers = Gmaps4rails.build_markers(@pool) do |pool, marker|
      p marker.lat pool.latitude
      p marker.lng pool.longitude
    end

    # price
    @price = @pool.price

  end

  def new
    @pool = Pool.new
  end

  def create
    params = pool_params
    @pool = Pool.new(params)
    current_user
    @pool.user = current_user
    @pool.availability = true
    if @pool.save
      redirect_to pool_path(@pool)
    else
      render :new
    end
  end

  private
    def find_user
      @user = current_user
    end

    def pool_params
      params.require(:pool).permit(:title, :address, :street_number, :route, :locality, :country, :price, :capacity, :availability, :content, :picture)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

      if user.persisted?
        sign_in_and_redirect user, event: :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    current_user.update(user_params)
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoolMouillee</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= csrf_meta_tags %>
  <title><%= yield(:title) || "Pool Mouillee" %></title>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render "shared/navbar" %>

  <div class="inner-body-minimum-height">
    <%= yield %>
  </div>

  <%= render "shared/footer" %>
  <!-- Google Maps -->

  <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyBYcAxl74WUjIEgd6IYCS-3RBNwC4D1DOc" %>



  <%= javascript_include_tag "application" %>

  <%= yield(:after_js) %>

  <%= javascript_tag do %>
    $(document).on('ready', function() {
      console.log('in the script');
      var notif = parseInt($('.notif').text());
      console.log(notif);
      if (notif > 0) {
        console.log('in the if');
        $('.notif').css('display','inline-block');
      }
    })
  <% end %>


</body>
</html>

app/views/pages/home.html.erb
<div class="homepage-hero-module">
  <div class="video-container" id="video-home">
    <div class="filter"></div>
    <video autoplay loop class="fillWidth">
       <source src="<%= video_path("poolmouillee.mp4")%>" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.

        <source src="<%= video_path("poolmouillee.webm")%>" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.

    </video>
  </div>
    <div class="poster hidden">
        <img src="<%= image_path("poolmouillee.jpg")%>">
    </div>
      <div class="container text-center" id="home_tagline">
        <h1>Pool Mouillée</h1>
        <p>Put on your best swimsuit and find a local a pool!</p>
      </div>
    <div id="home_search_bar" class="text-center">
      <div class="col-xs-offset-1 col-xs-10 col-sm-offset-0 col-sm-12">
        <div>
          <form action="/pools" method="get" class="form-inline">
            <div class="input-group">
              <label class="sr-only" for="city">City</label>
              <span class="input-group-addon"><i class="fa fa-search"></i></span>
              <input type="text" class="form-control" name="city" placeholder="City">
            </div>
            <div class="input-group">
              <label class="sr-only" for="checkin_on">Date</label>
              <input type="text" class='form-control checkin' name="checkin_on" placeholder="<%= Date.today.strftime("%d/%m/%Y") %>">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            </div>
            <div class="form-group">
              <label class="sr-only" for="length">Duration</label>
              <select class="form-control" name="length">
                <option>Morning</option>
                <option>Afternoon</option>
                <option>All Day</option>
                <option>All Night Long</option>
              </select>
            </div>
            <button type="submit" class="btn btn-default btn-danger">Pan Pan</button>
          </form>
        </div>
      </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('.checkin').datepicker({
          format: "dd/mm/yyyy",
          autoclose: true,
          todayHighlight: true
      });
    });
  <% end %>
<% end %>

app/views/pools/index.html.erb
<div class="container">
  <% if @nb_results == 0 %>
    <div class="row">
      <%= link_to "Back", :root, {class: "btn btn-primary", id: "btn-back"} %>
      <h1 id="city-display">Oops... looks like there's nothing there...</h1>
      <p class="text-center">Doesn't really matter... Grab a <i class="fa fa-beer"></i> and check out our awesome pools all around the world</p>
    </div>
    <div class="col-xs-12 " id="map-container">
      <div id="map" style="width: 100%; height: 500px;"></div>
    </div>
  <% else %>
    <div class="row">
      <%= link_to "Back", :root, {class: "btn btn-primary", id: "btn-back"} %>
      <h1 id="city-display">Available pools in <%= @city %></h1>
    </div>
    <div class="row">
      <div class="col-xs-12 col-lg-7" id="pools-box">
          <% @pools.each do |pool| %>
            <div class="col-xs-12 col-md-6 text-center" id="pool-thumb-info-box">
              <%= link_to(pool_path(id: pool.id, checkin_on: @checkin_on, length: @length)) do %>
                <div id="img-pool-index" style="background-image: url(<%= image_path pool.picture.url(:medium) %>);">
                  <p id="pool-title-display"><%= pool.title %></p>
                  <div id="pool-price">
                    <div class="price-integer">
                      <%= pool.price %>
                    </div>
                    <div id="euro">
                       €
                    </div>
                 </div>
                  <%= image_tag pool.user.profile_picture, {class: "img-circle", id: "img-user-index"}%>
                </div>
              <% end %>
              <div id="title-card">
              </div>
            </div>
          <% end %>
      </div>
      <div class="col-xs-12 col-lg-5 hidden-xs hidden-sm visible-md-* visible-lg-*" id="map-container">
        <div id="map" style="width: 100%; height: 500px;"></div>
      </div>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      var mapOptions = {
        disableDefaultUI: true
      }
       handler = Gmaps.build('Google');
      handler.buildMap({
        provider: { disableDefaultUI: true },
        internal: { id: 'map' }
        },
        function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
    })
  <% end %>
<% end %>

app/views/pools/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="card-white-content text-center" id="new-pool">
        <h3>New Pool</h3>

        <%= simple_form_for [@pool] do |f| %>
          <%= f.error_notification %>
          <h2 class="text-left mini-header">General information</h2>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-quote-left"></i></span>
            <%= f.input :title, label: false, placeholder: 'Give a sexy name to your pool' %>
          </div>
          <br>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
            <%= f.input :address, label: false, placeholder: 'Type your pool address'  %>
            <%= f.input :street_number, as: :hidden, name: "pool[street_number]", input_html: { id: "street_number"} %>
            <%= f.input :route, as: :hidden, name: "pool[route]", input_html: { id: "route"} %>
            <%= f.input :locality, as: :hidden, name: "pool[locality]", input_html: { id: "locality"} %>
            <%= f.input :country, as: :hidden, name: "pool[country]", input_html: { id: "country"} %>
          </div>
          <h2 class="text-left mini-header">Price and capacity</h2>
          <div class="input-group">
            <%= f.input :price, label: false, placeholder: 'Enter a price in €' %>
            <span class="input-group-addon"><i class="fa fa-eur"></i></span>
          </div>
          <br>
          <div class="input-group">
            <%= f.input :capacity, label: false, placeholder:'People capacity' %>
            <span class="input-group-addon"><i class="fa fa-users"></i></span>
          </div>
          <div class="form-group">
            <h2 class="text-left mini-header">Description</h2>
            <%= f.input :content, label: false, placeholder: 'Great pool! Sun is shining till late in afternoon, great to chill out by the pool with chicks!' %>
          </div>
          <div class="input-group">
            <h2 class="text-left mini-header"><i class="fa fa-camera-retro"></i> Add a picture for your pool</h2>
            <%= f.file_field :picture %>
          </div>
          <br>
            <%= f.button :submit, class: 'btn-danger confirm-pool' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <!-- Include Google Maps JS API -->

    <script type="text/javascript">
    function initializeAutocomplete(id) {
      var element = document.getElementById(id);
      if (element) {
        var autocomplete = new google.maps.places.Autocomplete(element, { types: ['geocode'] });
        console.log(element)
        google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
      }
    }

    function onPlaceChanged() {
      var place = this.getPlace();
      console.log(place);  // Uncomment this line to view the full object returned by Google API.
      for (var i in place.address_components) {
        var component = place.address_components[i];
        for (var j in component.types) {  // Some types are ["country", "political"]
          var type_element = document.getElementById(component.types[j]);
          if (type_element) {
            type_element.value = component.long_name;
          }
        }
      }
    }

    google.maps.event.addDomListener(window, 'load', function() {
      console.log('doing something');
      initializeAutocomplete('pool_address');
    });
  </script>
<% end %>

app/views/pools/show.html.erb
<div id="pool-big-pic" style="background-image: url(<%= image_path @pool.picture.url(:large) %>)">
  <h1></h1>
  <div id="map" class="map-circle map-right-corner"></div>
</div>
<div class="container-fluid" id="container-show">
  <div class="row">
    <div class="col-xs-12 col-md-3" id="side-box-padding">
      <div class="white-radius-box" id="owner-profile-box">
       <%= image_tag @pool.user.profile_picture, {class: "img-circle"}%>
        <h2><%= @pool.user.first_name + " " + @pool.user.last_name %><h2>
      </div>
    </div>
    <div class="col-xs-12 col-md-6" id="pool-description-box-padding">
      <div class="white-radius-box" id="pool-infos-box">
        <h2><%= @pool.title %></h2>
        <div id="capacity"><%= @pool.capacity %> <i class="fa fa-user"></i></div>
        <div>
          <h3><i class="fa fa-map-marker"></i><%= @pool.address %></h3>
          <p><%= @pool.content %></p>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-3" id="side-box-padding">
      <div class="white-radius-box" id="book-pool-box">
        <h2 id="h2-show-margin">Booking</h2>
        <div id="pool-price-booking">
          <div id="price-int">
            <%= @price %>
            </div>
          <div id="euro">
             €
          </div>
        </div>
        <% if current_user %>
          <% if @pool.availability %>
            <p><%= @message_to_user %></p>
            <%= form_for(@booking) do |f| %>
              <%= f.hidden_field :pool_id, :value => @pool.id.to_i %>
              <%= f.hidden_field :user_id, :value => current_user.id.to_i %>
              <div class="input-group" id="input-show">
                <%= f.text_field :checkin_on, :value => @checkin_on, :class => "form-control validate-checkin" %>
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              </div>
              <%= f.select :length, @length_selection, {}, {class: 'form-control ', id: "input-show"} %>

              <%= f.hidden_field :status, :value => "Pending" %>
              <%= f.submit "Confirm", :class => "btn btn-danger"  %>
            <% end %>
          <% else %>
            Pool not available.
          <% end %>
        <% else %>
            <%= image_tag("duck.jpg", height: '64') %>
            <%= link_to "Book this pool", new_user_registration_path, class: "btn btn-danger"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      var mapOptions = {
        disableDefaultUI: true
      }
      console.log(<%= raw @markers.to_json %>);
      handler = Gmaps.build('Google');
      handler.buildMap({
        provider: { disableDefaultUI: true },
        internal: { id: 'map' }
        },
        function(){
          markers = handler.addMarkers(<%= raw @markers.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.getMap().setZoom(14)
        });
    })
      $(document).ready(function(){
        $('.validate-checkin').datepicker({
            format: "dd/mm/yyyy",
            autoclose: true,
            todayHighlight: true
        });
      });
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-wagon" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "pool-mouillee2.png" %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#', { "data-toggle" => "dropdown", "aria-haspopup" => "true", "aria-expanded" => "false" } do %>
                <%= image_tag current_user.profile_picture, class:"img-avatar" %>
                <div class="notif"><p><%= current_user.notifications %></p></div>
                <span class='first-name' ><%= current_user.first_name %></span>
              <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu" aria-labelledby="dLabel">
                <li><%= link_to 'Profile', user_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

          <% else %>
            <li>
              <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path %>
            </li>
            <li>
              <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path %>
            </li>
          <% end %>
        <li>
          <% if user_signed_in? %>
            <%= link_to t(".top_call_to_action", default: "Add a pool"), new_pool_path, class:'btn btn-danger'%>
          <% else %>
            <%= link_to t(".top_call_to_action", default: "Add a pool"), new_user_registration_path, class:'btn btn-danger'%>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
<div class='container'>
  <div class="row">
    <div class='col-xs-12 col-md-3'>
      <div class='profile-container'>
        <div class="profile white-radius-box">
          <%= image_tag current_user.profile_picture, class:"img-profil-medium" %>
          <a role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false"><h4><%= current_user.first_name + ' ' + current_user.last_name %></h4></a>
          <div class="collapse" id="collapseExample">
            <ul>
              <li><%= link_to 'Edit profile', edit_user_path, class:'update-profile-links' %></li>
              <li><%= link_to 'Edit account', edit_user_registration_path(current_user), class:'update-profile-links'  %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class:'white-radius-box', class:'update-profile-links'  %></li>
            </ul>
          </div>
        </div>
        <div class='my-pools white-radius-box'>
          <% if current_user.pools.length == 1 %>
            <h4><%= current_user.pools.length%> pool</h4>
          <% else %>
            <h4><%= current_user.pools.length%> pools</h4>
          <% end %>
          <ul>
            <% current_user.pools.each do |pool| %>
              <li><%= link_to pool.title, pool_path(pool)%></li>
            <% end %>
          </ul>
          <button class='btn btn-red add-pool'><%= link_to 'Add a pool', new_pool_path %></button>
        </div>
      </div>
    </div>
    <div class='col-xs-12 col-md-9'>
      <div class='main-container'>

        <div class='my-bookings white-radius-box'>
          <h3>My Bookings</h3>
          <table class='table table-hover text-align-left'>
            <th class='hidden-responsive'></th>
            <th>Pool</th>
            <th>Date</th>
            <th class='hidden-responsive'>Lenght</th>
            <th>Status</th>
            <% current_user.bookings.each do |booking| %>
              <tr>
                <td class='vert-align hidden-responsive'>
                  <%= link_to pool_path(booking.pool) do %>
                    <%= image_tag booking.pool.picture.url(:thumbnail), class:'img-pools-request' %>
                  <% end %>
                </td>
                <td class='vert-align'><strong><%= booking.pool.title %></strong></td>
                <td class='vert-align'><%= booking.checkin_on %></td>
                <td class='vert-align hidden-responsive'><%= booking.length %>
                  <% if booking.status == 'Pending' %>
                     <td class='vert-align text-orange'><strong><i class="fa fa-clock-o"></i> <%= booking.status %></strong></td>
                  <% elsif booking.status == 'Confirmed' %>
                    <td class='vert-align text-green'><strong><i class="fa fa-check"></i> <%= booking.status %></strong></td>
                  <% else %>
                    <td class='vert-align text-red'><strong><i class="fa fa-times"></i> <%= booking.status %></strong></td>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>

        <div class='my-pool-requests white-radius-box'>
          <h3>My Pools Requests</h3>
          <table class='table'>
            <th class='hidden-responsive'></th>
            <th class='hidden-responsive'>Guest</th>
            <th>Pool</th>
            <th>Date</th>
            <th class='hidden-responsive'>Status</th>
            <th>Action</th>
              <% current_user.pools.each do |pool| %>
                <% pool.bookings.each do |booking| %>
                  <tr>
                    <% if booking.user.provider %>
                      <td class='vert-align hidden-responsive'><%= image_tag booking.user.facebook_picture, class:"img-pools-request" %></td>
                    <% else %>
                      <td class='vert-align hidden-responsive'><%= image_tag booking.user.picture(:thumb), class:"img-pools-request" %></td>
                    <% end %>
                    <td class='vert-align hidden-responsive'><strong><%= booking.user.first_name + ' ' + booking.user.last_name %></strong></td>
                    <td class='vert-align'><%= booking.pool.title %></td>
                    <td class='vert-align'><%= booking.checkin_on %></td>
                      <% if booking.status == 'Pending' %>
                        <td class='vert-align text-orange'>
                          <ul class='list-inline  hidden-responsive'>
                            <li><strong><i class="fa fa-clock-o"></strong></i></li>
                            <li><strong><%= booking.status %></strong></li>
                          </ul>
                        </td>
                        <td class='vert-align'>
                        <ul class='list-inline'>
                            <li><%= button_to 'Confirm', {controller: :bookings, action: :update, id: booking.id }, params: {status: 'Confirmed'}, method: :patch, class:'btn-green' %></li>
                            <li><%= button_to 'Refuse', {controller: :bookings, action: :update, id: booking.id }, params: {status: 'Refused'}, method: :patch, class:'btn-red'%></li>
                            </ul>
                        </td>
                      <% else %>
                        <% if booking.status == 'Confirmed' %>
                          <td class='vert-align text-green hidden-responsive'>
                            <ul class='list-inline'>
                              <li><strong><i class="fa fa-check"></i></strong></li>
                              <li><strong><%= booking.status %></strong></li>
                            </ul>
                          </td>
                          <td class='vert-align responsive-left'>
                            <%= button_to 'Cancel', {controller: :bookings, action: :update, id: booking.id }, params: {status: 'Refused'}, method: :patch, class:'btn-red' %>
                          </td>
                        <% else %>
                          <td class='vert-align text-red hidden-responsive'>
                            <ul class='list-inline'>
                              <li><strong><i class="fa fa-times"></strong></i></li>
                              <li><strong><%= booking.status %></strong></li>
                            </ul>
                          </td>
                          <td class='vert-align responsive-left'>
                            <%= button_to 'Accept', {controller: :bookings, action: :update, id: booking.id }, params: {status: 'Confirmed'}, method: :patch, class:'btn-green' %>
                          </td>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>